---
name: Clean Validation Environments

on:  # yamllint disable-line rule:truthy
  schedule:
  workflow_dispatch:

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    environment: CICD
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          # This is CRITICAL since we're making decisions based on branch existence
          fetch-depth: 0
          persist-credentials: false

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAIN_TRE_ID: ${{ secrets.TRE_ID }}
          BRANCH_LAST_ACTIVITY_IN_HOURS: 2
        run: devops/scripts/clean_ci_validation_envs.sh
